#!/usr/bin/env python
import os
inter = input("Enter standart network interface!:")
apinter = input("Enter your network interface with support access point!:")
os.system('echo "bind-interfaces" >> /etc/dnsmasq.conf')
interfaces = ('echo "interface=') + (apinter) + ('" >> /etc/dnsmasq.conf')
os.system(interfaces)
os.system('echo "dhcp-range=192.168.150.2,192.168.150.10" >> /etc/dnsmasq.conf')
os.system("cd && cd X-TOOL && touch hostapd.sh")
os.system('echo "#!/bin/bash" >> /hostapd.sh')
ifconfig = ('cd && cd X-TOOL && echo "') + ("ifconfig ") + (apinter) + (" 192.168.150.1") + ('" >> hostapd.sh')
os.system(ifconfig)
os.system('cd && cd X-TOOL && chmod +x * && echo "service dnsmasq restart" >> hostapd.sh')
os.system('cd && cd X-TOOL && chmod +x * && echo "sysctl net.ipv4.ip_forward=1" >> hostapd.sh')
os.system('cd && cd X-TOOL && chmod +x * && echo "iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE" >> hostapd.sh')
os.system('cd && cd X-TOOL && chmod +x * && echo "hostapd /X-TOOL/hostapd.conf" >> hostapd.sh')
ip2 = ('cd && cd X-TOOL && chmod +x * && echo "iptables -D POSTROUTING -t nat -o ') + (inter) + (' -j MASQUERADE" >> hostapd.sh')
os.system(ip2)
os.system('cd && cd X-TOOL && chmod +x * && echo "sysctl net.ipv4.ip_forward=0" >> hostapd.sh')
os.system('cd && cd X-TOOL && chmod +x * && echo "service dnsmasq stop" >> hostapd.sh')
os.system('cd && cd X-TOOL && chmod +x * && echo "service hostapd stop" >> hostapd.sh')
inte = ('cd && cd X-TOOL && chmod +x * && echo "') + ("interface=") + (apinter) + ('" >> hostapd.conf')
os.system(inte)
os.system('cd && cd X-TOOL && chmod +x * && echo "driver=nl80211" >> hostapd.conf')
os.system('cd && cd X-TOOL && chmod +x * && echo "ssid=FreeWiFi" >> hostapd.conf')
os.system('cd && cd X-TOOL && chmod +x * && echo "hw_mode=g" >> hostapd.conf')
os.system('cd && cd X-TOOL && chmod +x * && echo "channel=6" >> hostapd.conf')